const Actions = {
    CONFIRM_SHOW: "CONFIRM_SHOW",
    CONFIRM_HIDE: "CONFIRM_HIDE",

    WAD_UPLOAD: "WAD_UPLOAD",
    WAD_RENAME: "WAD_RENAME",

    ROUTER_GOTO_PAGE: "ROUTER_GOTO_PAGE",
    ROUTER_GOTO_PREVIOUS: "ROUTER_GOTO_PREVIOUS",

    NAVIGATION_SET_TITLE: "NAVIGATION_SET_TITLE",
    NAVIGATION_ENABLE_BACK: "NAVIGATION_ENABLE_BACK",

    MESSAGES_SEND:"MESSAGES_SEND"
}

export default Actions;