const ACTIONS = {
    CONFIRM_SHOW: "CONFIRM_SHOW",
    CONFIRM_HIDE: "CONFIRM_HIDE",

    WADS_UPLOADED: "WADS_UPLOADED",
    WADS_EDIT_START: "WADS_EDIT_START",
    WADS_EDIT_END: "WADS_EDIT_END",

    ROUTER_GOTO_PAGE: "ROUTER_GOTO_PAGE",
}

export default ACTIONS;