const ACTIONS = {
    CONFIRM_SHOW: "CONFIRM_SHOW",
    CONFIRM_HIDE: "CONFIRM_HIDE",

    WAD_UPLOADED: "WAD_UPLOADED",

    ROUTER_GOTO_PAGE: "ROUTER_GOTO_PAGE",
    ROUTER_GOTO_PREVIOUS: "ROUTER_GOTO_PREVIOUS",

    NAVIGATION_SET_TITLE: "NAVIGATION_SET_TITLE",

    MESSAGES_SEND:"MESSAGES_SEND"
}

export default ACTIONS;